

#_meta.script_name: start-host
#
#_base: [flask]

#_meta.script_name: test-dummy
#_meta.script_name: uplink
_meta.script_name: start-bot

admins: [felixludos#0]

server-name: games

#client._type: murder-bot
#client._type: wise-bot
#client._type: unwise-bot
#client._type: dixit-bot
#client._type: mysterium-bot
#client._type: mysticdialogue-bot
#client._type: wits-bot
client._type: witi-bot

#client._type: sheriff-bot

#client._type: diplomacy-bot


seed: 7




