

#_meta.script_name: start-host
#
#parents: [flask]

#_meta.script_name: test-dummy
#_meta.script_name: uplink
_meta.script_name: start-bot

admins: [felixludos#9043]


#client._type: murder-bot

#client._type: wise-bot
#client._type: sheriff-bot

client._type: unwise-bot

#seed: 7
